units_type: character
feature_source: kaldi
feature_type: mfcc
data:
    name: timit
    vocab: egs/timit/data/vocab
    left_context_width: 0
    right_context_width: 0
    frame_rate: 10
    apply_cmvn: True
    max_input_length: 2000
    max_target_length: 100
    batch_size: 1
    encoding: True
    short_first: True
    shuffle: False
    text_flag: text
    train: egs/timit/data/train
    dev: egs/timit/data/dev
    test: egs/timit/data/test
model:
    type: transducer
    enc:
        type: lstm
        hidden_size: 128
        output_size: 128
        n_layers: 3
        bidirectional: True
    dec:
        type: lstm
        hidden_size: 256
        output_size: 128
        n_layers: 1
    joint:
        input_size: 256
        inner_size: 128
    vocab_size: 49
    share_weight: False
    feature_dim: 40
    dropout: 0.3
    backend: c++
training:
    load_model: False
    load_encoder: False
    load_decoder: False
    eval_or_not: True
    seed: 2019
    num_gpu: 1
    epoches: 1000
    max_grad_norm: 200
    visualization: True
    show_interval: 10
    save_model: 3blstm_128henc_1l256dec
optim:
    type: sgd
    lr: 0.0001
    momentum: 0.9
    decay_ratio: 0.5
    weight_decay: 0
    begin_to_adjust_lr: 10
